const DEFAULT_URL="https://raw.githubusercontent.com/Ashok-Kumar-Yadaw/IPTV-INDIA/main/in.m3u";
const K={url:"iptv4-url",cache:"iptv4-cache",fav:"iptv4-fav",recent:"iptv4-recent",theme:"iptv4-theme",last:"iptv4-last",auto:"iptv4-auto",refresh:"iptv4-refresh"};
const $=id=>document.getElementById(id), get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}, put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let S={channels:[],cat:"All",q:"",fav:false,recent:false,sort:false}, favs=new Set(get(K.fav,[])),recent=get(K.recent,[]);
const player=videojs("player",{controls:true,responsive:true,fluid:true,liveui:true,preload:"metadata",html5:{vhs:{overrideNative:true,enableLowInitialPlaylist:true,limitRenditionByPlayerDimensions:true}}});
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function parse(text){let l=text.replace(/\r/g,"").split("\n"),o=[];for(let i=0;i<l.length;i++){let x=l[i].trim();if(!x.startsWith("#EXTINF"))continue;let a={},m,re=/([A-Za-z0-9_-]+)="([^"]*)"/g,c=x.indexOf(",");while(m=re.exec(x))a[m[1]]=m[2];let name=(c>=0?x.slice(c+1).trim():a["tvg-name"])||"Unknown";let url="";for(let j=i+1;j<l.length;j++){let n=l[j].trim();if(!n||n[0]==="#")continue;url=n;i=j;break}if(url)o.push({name,group:a["group-title"]||"Other",logo:a["tvg-logo"]||"",id:a["tvg-id"]||"",url,lang:a["tvg-language"]||"",epg:a["tvg-id"]||""})}return o}
function cat(c){let s=(c.group+" "+c.name).toLowerCase();if(/news|न्यूज़|समाचार/.test(s))return"News";if(/movie|film|cinema|मूवी|फिल्म/.test(s))return"Movies";if(/music|म्यूजिक|संगीत/.test(s))return"Music";if(/sport|खेल/.test(s))return"Sports";if(/kids|cartoon|बच्च/.test(s))return"Kids";if(/bhakti|devotional|spiritual|भक्ति|धार्मिक/.test(s))return"Devotional";if(/entertainment|मनोरंजन/.test(s))return"Entertainment";return c.group||"Other"}
function renderCats(){let n={};S.channels.forEach(c=>n[cat(c)]=(n[cat(c)]||0)+1);let all=["All",...Object.keys(n).sort()];$("cats").innerHTML=all.map(x=>`<button class="cat ${x===S.cat?"active":""}" data-c="${esc(x)}">${esc(x)}${x!=="All"?` (${n[x]})`:""}</button>`).join("");$("cats").querySelectorAll(".cat").forEach(b=>b.onclick=()=>{S.cat=b.dataset.c;renderCats();render()})}
function visible(){let q=S.q.toLowerCase().trim(),a=S.channels.filter(c=>(S.cat==="All"||cat(c)===S.cat)&&(!q||(c.name+" "+c.group+" "+c.lang).toLowerCase().includes(q))&&(!S.fav||favs.has(c.id||c.url))&&(!S.recent||recent.includes(c.url)));if(S.sort)a.sort((a,b)=>a.name.localeCompare(b.name));return a}
function makeCard(c,mini=false){let key=c.id||c.url,d=document.createElement("article");d.className=mini?"mini":"card";d.innerHTML=`<div class="ct"><img class="logo" loading="lazy" src="${esc(c.logo)}" alt="" onerror="this.removeAttribute('src')"><div class="nm">${esc(c.name)}</div>${mini?"":`<button class="star">${favs.has(key)?"★":"☆"}</button>`}</div><div class="meta">${esc(cat(c))} · ${esc(c.group)}${c.lang?" · "+esc(c.lang):""}</div>`;d.onclick=e=>{if(e.target.closest(".star")){e.stopPropagation();favs.has(key)?favs.delete(key):favs.add(key);put(K.fav,[...favs]);render();return}play(c)};return d}
function render(){let a=visible();$("count").textContent=`${a.length} / ${S.channels.length} channels`;let g=$("grid");g.innerHTML="";if(!a.length){g.innerHTML='<div class="empty">कोई channel नहीं मिला।</div>';return}let i=0;function chunk(){let f=document.createDocumentFragment(),end=Math.min(i+70,a.length);for(;i<end;i++)f.appendChild(makeCard(a[i]));g.appendChild(f);if(i<a.length)requestAnimationFrame(chunk)}chunk();renderHome()}
function renderHome(){let gs=["News","Movies","Music","Sports","Entertainment"],h="";for(let x of gs){let a=S.channels.filter(c=>cat(c)===x).slice(0,12);if(!a.length)continue;h+=`<div class="row-title"><h2>${x}</h2><span>${a.length}+ channels</span></div><div class="row" data-row="${x}"></div>`}$("home").innerHTML=h;for(let x of gs){let r=document.querySelector(`[data-row="${x}"]`);if(r)S.channels.filter(c=>cat(c)===x).slice(0,12).forEach(c=>r.appendChild(makeCard(c,true)))}}
function play(c){$("playing").textContent="▶ "+c.name;$("status").textContent="Connecting…";$("buffer").classList.remove("hidden");$("live").classList.remove("hidden");recent=[c.url,...recent.filter(x=>x!==c.url)].slice(0,30);put(K.recent,recent);put(K.last,c.url);player.src({src:c.url,type:/\.m3u8($|\?)/i.test(c.url)?"application/x-mpegURL":"video/mp4"});player.play().catch(()=>{})}
player.on("playing",()=>{$("status").textContent="● Live / Playing";$("buffer").classList.add("hidden")});player.on("waiting",()=>{$("status").textContent="Buffering…";$("buffer").classList.remove("hidden")});player.on("error",()=>{ $("status").textContent="Stream error — retrying…";setTimeout(()=>{try{player.play().catch(()=>{})}catch{}},1500)});
$("pip").onclick=()=>player.requestPictureInPicture?.().catch(()=>{});$("full").onclick=()=>player.requestFullscreen?.();
$("quality").onclick=()=>{let t=player.tech({IWillNotUseThisInPlugins:true});let q=t?.vhs?.representations?.()||[];show(`<h2>Quality</h2>${q.length?q.map((x,i)=>`<button class="save" style="margin:4px" data-q="${i}">${x.width||"Auto"}p</button>`).join(""):"<p class='hint'>इस stream में browser-level quality variants उपलब्ध नहीं हैं। HLS adaptive selection अपने आप होगा।"}`);document.querySelectorAll("[data-q]").forEach((b,i)=>b.onclick=()=>{q.forEach((x,j)=>x.enabled(j===i));closeModal()})};
async function load(force=false){let url=localStorage.getItem(K.url)||DEFAULT_URL;if(!force){let c=get(K.cache,null);if(c?.channels?.length){S.channels=c.channels;renderCats();render();$("status").textContent="Cached playlist";setTimeout(()=>load(true),500);return}}try{$("status").textContent="Loading playlist…";let r=await fetch(url+"?t="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error(r.status);let channels=parse(await r.text());if(!channels.length)throw Error("empty");S.channels=channels;put(K.cache,{time:Date.now(),channels});renderCats();render();$("status").textContent=`Updated · ${channels.length} channels`}catch(e){console.error(e);$("status").textContent="Playlist update failed";if(!S.channels.length)$("grid").innerHTML='<div class="empty">Playlist load नहीं हो सकी।</div>'}}
$("search").oninput=e=>{clearTimeout(window.qq);window.qq=setTimeout(()=>{S.q=e.target.value;render()},120)};$("fav").onclick=()=>{S.fav=!S.fav;$("fav").classList.toggle("active",S.fav);render()};$("recent").onclick=()=>{S.recent=!S.recent;$("recent").classList.toggle("active",S.recent);render()};$("sort").onclick=()=>{S.sort=!S.sort;$("sort").classList.toggle("active",S.sort);render()};$("refresh").onclick=()=>load(true);
function show(html){$("modalBody").innerHTML=html;$("modal").classList.remove("hidden")}function closeModal(){$("modal").classList.add("hidden")}$("close").onclick=closeModal;
$("guideBtn").onclick=()=>guide();$("healthBtn").onclick=()=>health();$("statsBtn").onclick=()=>stats();
function guide(){let rows=S.channels.slice(0,100).map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.group)}</td><td>${c.lang?esc(c.lang):"—"}</td><td>EPG metadata${c.epg?" ✓":" —"}</td></tr>`).join("");show(`<h2>📅 TV Guide</h2><p class="hint">EPG/XMLTV URL उपलब्ध होने पर वास्तविक कार्यक्रम यहाँ जोड़े जा सकते हैं। अभी playlist metadata आधारित channel guide है।</p><table><tr><th>Channel</th><th>Category</th><th>Language</th><th>EPG</th></tr>${rows}</table>`)}
async function health(){show("<h2>🟢 Channel Health</h2><p class='hint'>Browser security/CORS के कारण सभी remote streams का reliable health-check संभव नहीं है। Player से चलाए गए channels की स्थिति यहाँ दिखाई जा सकती है।</p><table><tr><th>Channel</th><th>Status</th></tr>"+S.channels.slice(0,100).map(c=>`<tr><td>${esc(c.name)}</td><td class="warn">Not tested</td></tr>`).join("")+"</table>")}
function stats(){let groups={};S.channels.forEach(c=>groups[cat(c)]=(groups[cat(c)]||0)+1);show(`<h2>📊 Playlist Stats</h2><p><b>Total:</b> ${S.channels.length}</p><p><b>Favorites:</b> ${favs.size}</p><p><b>Recently watched:</b> ${recent.length}</p><table><tr><th>Category</th><th>Channels</th></tr>${Object.entries(groups).sort().map(([a,b])=>`<tr><td>${esc(a)}</td><td>${b}</td></tr>`).join("")}</table>`)}

function openSettings(){show(`<h2>⚙ Settings</h2><label>Playlist URL<input id="setUrl" value="${esc(localStorage.getItem(K.url)||DEFAULT_URL)}"></label><label>Auto refresh (minutes)<input id="setRefresh" type="number" min="1" value="${localStorage.getItem(K.refresh)||30}"></label><label><input id="setAuto" type="checkbox" ${localStorage.getItem(K.auto)!=="0"?"checked":""}> Last channel restore</label><br><button id="saveSet" class="save">Save settings</button><p class="hint">Settings are stored only in this browser.</p>`);$("saveSet").onclick=()=>{localStorage.setItem(K.url,$("setUrl").value.trim()||DEFAULT_URL);localStorage.setItem(K.refresh,$("setRefresh").value||30);localStorage.setItem(K.auto,$("setAuto").checked?"1":"0");closeModal();load(true)}}
$("settings").onclick=openSettings;
document.querySelectorAll(".bottom button").forEach(b=>b.onclick=()=>{let n=b.dataset.nav;if(n==="settings")openSettings();else if(n==="guide")guide();else if(n==="favorites"){$("fav").click();scrollTo({top:260,behavior:"smooth"})}else if(n==="live"){S.fav=S.recent=false;$("fav").classList.remove("active");$("recent").classList.remove("active");render();scrollTo({top:260,behavior:"smooth"})}else scrollTo({top:0,behavior:"smooth"})});
function theme(t){document.documentElement.dataset.theme=t;localStorage.setItem(K.theme,t);$("theme").textContent=t==="dark"?"☀️":"🌙"}theme(localStorage.getItem(K.theme)||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light"));$("theme").onclick=()=>theme(document.documentElement.dataset.theme==="dark"?"light":"dark");
let dp;addEventListener("beforeinstallprompt",e=>{e.preventDefault();dp=e;$("install").classList.remove("hidden")});$("install").onclick=async()=>{await dp?.prompt();dp=null;$("install").classList.add("hidden")};if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(console.warn));
load();setInterval(()=>load(true),Number(localStorage.getItem(K.refresh)||30)*60000);
