const DEFAULT="https://raw.githubusercontent.com/Ashok-Kumar-Yadaw/IPTV-INDIA/main/in.m3u";
const KEY={sources:"v6-sources",cache:"v6-cache",fav:"v6-fav",recent:"v6-recent",theme:"v6-theme",refresh:"v6-refresh",epg:"v6-epg",rem:"v6-reminders",analytics:"v6-analytics"};
const $=x=>document.getElementById(x),read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let sources=read(KEY.sources,[{name:"IPTV INDIA",url:DEFAULT}]), activeSource=0,S={channels:[],cat:"All",q:"",fav:false,recent:false},favs=new Set(read(KEY.fav,[])),recent=read(KEY.recent,[]),events=read(KEY.analytics,[]);
const player=videojs("player",{controls:true,responsive:true,fluid:true,liveui:true,preload:"metadata",html5:{vhs:{overrideNative:true,enableLowInitialPlaylist:true,limitRenditionByPlayerDimensions:true}}});
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function parse(t){let a=t.replace(/\r/g,"").split("\n"),o=[],num=0;for(let i=0;i<a.length;i++){let l=a[i].trim();if(!l.startsWith("#EXTINF"))continue;let m={},r=/([A-Za-z0-9_-]+)="([^"]*)"/g,x,c=l.indexOf(",");while(x=r.exec(l))m[x[1]]=x[2];let name=(c>=0?l.slice(c+1).trim():m["tvg-name"])||"Unknown",url="";for(let j=i+1;j<a.length;j++){let n=a[j].trim();if(!n||n[0]==="#")continue;url=n;i=j;break}if(url)o.push({num:++num,name,group:m["group-title"]||"Other",logo:m["tvg-logo"]||"",id:m["tvg-id"]||"",url,lang:m["tvg-language"]||"",epg:m["tvg-id"]||""})}return o}
function cat(c){let s=(c.group+" "+c.name).toLowerCase();if(/news|न्यूज़|समाचार/.test(s))return"News";if(/movie|film|cinema|मूवी|फिल्म/.test(s))return"Movies";if(/music|म्यूजिक|संगीत/.test(s))return"Music";if(/sport|खेल/.test(s))return"Sports";if(/kids|cartoon|बच्च/.test(s))return"Kids";if(/bhakti|devotional|spiritual|भक्ति|धार्मिक/.test(s))return"Devotional";if(/entertainment|मनोरंजन/.test(s))return"Entertainment";return c.group||"Other"}
function sourceUI(){ $("source").innerHTML=sources.map((s,i)=>`<option value="${i}" ${i===activeSource?"selected":""}>${esc(s.name)}</option>`).join("")}
function cats(){let n={};S.channels.forEach(c=>n[cat(c)]=(n[cat(c)]||0)+1);$("cats").innerHTML=["All",...Object.keys(n).sort()].map(x=>`<button class="cat ${x===S.cat?"on":""}" data-c="${esc(x)}">${esc(x)}${x==="All"?"":` (${n[x]})`}</button>`).join("");document.querySelectorAll(".cat").forEach(b=>b.onclick=()=>{S.cat=b.dataset.c;cats();render()})}
function visible(){let q=S.q.toLowerCase().trim(),a=S.channels.filter(c=>(S.cat==="All"||cat(c)===S.cat)&&(!q||(c.name+" "+c.group+" "+c.lang+" "+c.num).toLowerCase().includes(q))&&(!S.fav||favs.has(c.id||c.url))&&(!S.recent||recent.includes(c.url)));return a.sort((x,y)=>x.name.localeCompare(y.name))}
function card(c,mini=false){let key=c.id||c.url,d=document.createElement("article");d.className=mini?"mini":"card";d.innerHTML=`<div class="ct"><img class="logo" loading="lazy" src="${esc(c.logo)}" onerror="this.removeAttribute('src')"><div class="nm">${esc(c.num)}. ${esc(c.name)}</div>${mini?"":`<button class="star">${favs.has(key)?"★":"☆"}</button>`}</div><div class="meta">${esc(cat(c))} · ${esc(c.group)}${c.lang?" · "+esc(c.lang):""}</div>`;d.onclick=e=>{if(e.target.closest(".star")){e.stopPropagation();favs.has(key)?favs.delete(key):favs.add(key);save(KEY.fav,[...favs]);render();return}play(c)};return d}
function render(){let a=visible();$("count").textContent=`${a.length} / ${S.channels.length} channels`;let g=$("grid");g.innerHTML="";if(!a.length){g.innerHTML='<div class="empty">कोई channel नहीं मिला।</div>';return}let i=0;function chunk(){let f=document.createDocumentFragment(),end=Math.min(i+80,a.length);for(;i<end;i++)f.appendChild(card(a[i]));g.appendChild(f);if(i<a.length)requestAnimationFrame(chunk)}chunk();home()}
function home(){let groups=["News","Movies","Music","Sports","Entertainment"],h="";for(let x of groups){let a=S.channels.filter(c=>cat(c)===x).slice(0,12);if(!a.length)continue;h+=`<div class="rowtitle"><h2>${x}</h2><span>${a.length}+ channels</span></div><div class="row" data-row="${x}"></div>`}$("home").innerHTML=h;for(let x of groups){let r=document.querySelector(`[data-row="${x}"]`);if(r)S.channels.filter(c=>cat(c)===x).slice(0,12).forEach(c=>r.appendChild(card(c,true)))}}
function play(c){$("now").textContent="▶ "+c.name;$("state").textContent="Connecting…";$("buf").classList.remove("hide");$("live").classList.remove("hide");recent=[c.url,...recent.filter(x=>x!==c.url)].slice(0,50);save(KEY.recent,recent);localStorage.setItem("v6-last",c.url);events.push({url:c.url,name:c.name,at:Date.now()});events=events.slice(-500);save(KEY.analytics,events);player.src({src:c.url,type:/\.m3u8($|\?)/i.test(c.url)?"application/x-mpegURL":"video/mp4"});player.play().catch(()=>{});scheduleReminders(c)}
player.on("playing",()=>{$("state").textContent="● Live / Playing";$("buf").classList.add("hide")});player.on("waiting",()=>{$("state").textContent="Buffering…";$("buf").classList.remove("hide")});player.on("error",()=>{$("state").textContent="Stream error — retrying…";setTimeout(()=>player.play().catch(()=>{}),1400)});
$("pip").onclick=()=>player.requestPictureInPicture?.().catch(()=>{});$("full").onclick=()=>player.requestFullscreen?.();
$("quality").onclick=()=>{let reps=player.tech({IWillNotUseThisInPlugins:true})?.vhs?.representations?.()||[];modal(`<h2>Quality</h2>${reps.length?reps.map((r,i)=>`<button class="save q" data-i="${i}">${r.width||"Auto"}p</button>`).join(" "):"<p class='hint'>Stream ने quality variants expose नहीं किए हैं। Adaptive HLS उपलब्ध होने पर player खुद चुन सकता है।"}`);document.querySelectorAll(".q").forEach(b=>b.onclick=()=>{reps.forEach((r,j)=>r.enabled(j===+b.dataset.i));close()})};
async function load(force=false){let url=sources[activeSource]?.url||DEFAULT,cache=read(KEY.cache,{}),ck=cache[url];if(!force&&ck?.channels?.length){S.channels=ck.channels;cats();render();$("state").textContent="Cached playlist";setTimeout(()=>load(true),500);return}try{$("state").textContent="Loading playlist…";let r=await fetch(url+"?t="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error(r.status);let a=parse(await r.text());if(!a.length)throw Error("empty");S.channels=a;cache[url]={time:Date.now(),channels:a};save(KEY.cache,cache);cats();render();$("state").textContent=`Updated · ${a.length} channels`}catch(e){$("state").textContent="Playlist update failed";if(!S.channels.length)$("grid").innerHTML='<div class="empty">Playlist load नहीं हो सकी। CORS या URL check करें।</div>'}}
function modal(h){$("modalBody").innerHTML=h;$("modal").classList.remove("hide")}function close(){$("modal").classList.add("hide")}$("close").onclick=close;
function guide(){let epg=localStorage.getItem(KEY.epg)||"";modal(`<h2>📅 EPG TV Guide</h2><p class="hint">XMLTV URL सेट करने पर इस UI को real programme data से जोड़ा जा सकता है। Browser CORS अनुमति आवश्यक हो सकती है।</p><label>XMLTV/EPG URL<input id="epg" type="url" value="${esc(epg)}"></label><button id="saveEpg" class="save">Save EPG URL</button><hr><table><tr><th>#</th><th>Channel</th><th>Category</th><th>EPG ID</th></tr>${S.channels.slice(0,150).map(c=>`<tr><td>${c.num}</td><td>${esc(c.name)}</td><td>${esc(cat(c))}</td><td>${esc(c.epg||"—")}</td></tr>`).join("")}</table>`);$("saveEpg").onclick=()=>{localStorage.setItem(KEY.epg,$("epg").value.trim());close()}}
function reminders(){let r=read(KEY.rem,[]);modal(`<h2>🔔 Program Reminders</h2><p class="hint">EPG data उपलब्ध होने पर reminders को programme start time से जोड़ा जा सकता है। अभी आप browser notification permission और saved reminders देख सकते हैं।</p><button id="notify" class="save">Enable Notifications</button><table><tr><th>Program</th><th>Time</th></tr>${r.length?r.map(x=>`<tr><td>${esc(x.title)}</td><td>${new Date(x.at).toLocaleString()}</td></tr>`).join(""):"<tr><td colspan=2>No reminders</td></tr>"}</table>`);$("notify").onclick=async()=>{if("Notification"in window){let p=await Notification.requestPermission();alert("Notification: "+p)}else alert("Browser notifications unavailable")}}
function scheduleReminders(c){let r=read(KEY.rem,[]).filter(x=>x.at>Date.now());r.forEach(x=>{if(x.url===c.url&&x.at-Date.now()<86400000)setTimeout(()=>notify(x),Math.max(0,x.at-Date.now()))});save(KEY.rem,r)}
function notify(x){if("Notification"in window&&Notification.permission==="granted")new Notification("IPTV INDIA",{body:x.title})}
function health(){modal(`<h2>🟢 Channel Health</h2><p class="hint">Browser arbitrary remote URLs को reliable तरीके से probe नहीं कर सकता। यह screen false online/offline claims नहीं करती। Actual playback state ऊपर player में दिखता है।</p><table><tr><th>Channel</th><th>Status</th></tr>${S.channels.slice(0,120).map(c=>`<tr><td>${esc(c.name)}</td><td class="warn">Not probed</td></tr>`).join("")}</table>`)}
function cleaner(){let seen=new Set(),dupes=[],clean=[];for(let c of S.channels){let k=(c.id||c.name+"|"+c.url).toLowerCase();if(seen.has(k))dupes.push(c);else{seen.add(k);clean.push(c)}}modal(`<h2>🧹 Playlist Cleaner</h2><p>Total: <b>${S.channels.length}</b> · Potential duplicates: <b>${dupes.length}</b></p><button id="export" class="save">Export cleaned M3U</button>`);$("export").onclick=()=>{let t="#EXTM3U\\n"+clean.map(c=>`#EXTINF:-1 tvg-id="${esc(c.id)}" tvg-name="${esc(c.name)}" tvg-logo="${esc(c.logo)}" group-title="${esc(c.group)}",${c.name}\\n${c.url}`).join("\\n");download("iptv-india-clean.m3u",t,"audio/x-mpegurl")}}
function stats(){let g={};S.channels.forEach(c=>g[cat(c)]=(g[cat(c)]||0)+1);let top=Object.entries(g).sort((a,b)=>b[1]-a[1]);modal(`<h2>📊 Usage & Playlist Stats</h2><p>Total: <b>${S.channels.length}</b> · Favorites: <b>${favs.size}</b> · Recent: <b>${recent.length}</b> · Plays: <b>${events.length}</b></p><table><tr><th>Category</th><th>Channels</th></tr>${top.map(([x,n])=>`<tr><td>${esc(x)}</td><td>${n}</td></tr>`).join("")}</table>`)}
function addSource(){modal(`<h2>＋ Add Playlist</h2><label>Name<input id="sn" type="text" placeholder="My Playlist"></label><label>M3U URL<input id="su" type="url" placeholder="https://example.com/list.m3u"></label><button id="add" class="save">Add</button>`);$("add").onclick=()=>{let n=$("sn").value.trim()||"Playlist "+(sources.length+1),u=$("su").value.trim();if(!u)return alert("URL required");sources.push({name:n,url:u});save(KEY.sources,sources);activeSource=sources.length-1;sourceUI();close();load(true)}}
function settings(){modal(`<h2>⚙ Settings</h2><label>Auto refresh (minutes)<input id="rf" type="number" min="1" value="${localStorage.getItem(KEY.refresh)||30}"></label><label><input id="auto" type="checkbox" ${localStorage.getItem("v6-auto")!=="0"?"checked":""}> Restore last channel</label><button id="save" class="save">Save</button><button id="backup" class="save">Backup</button><input id="restore" type="file" accept=".json">`);$("save").onclick=()=>{localStorage.setItem(KEY.refresh,$("rf").value||30);localStorage.setItem("v6-auto",$("auto").checked?"1":"0");close()};$("backup").onclick=()=>download("iptv-india-v6-backup.json",JSON.stringify({sources,favorites:[...favs],recent,epg:localStorage.getItem(KEY.epg)||""},null,2),"application/json");$("restore").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(x.sources){sources=x.sources;save(KEY.sources,sources)}if(x.favorites){favs=new Set(x.favorites);save(KEY.fav,[...favs])}if(x.recent){recent=x.recent;save(KEY.recent,recent)}if(x.epg)localStorage.setItem(KEY.epg,x.epg);location.reload()}catch{alert("Invalid backup")}};r.readAsText(f)}}
function download(n,t,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("source").onchange=e=>{activeSource=+e.target.value;S.channels=[];load(false)};$("addSource").onclick=addSource;$("search").oninput=e=>{clearTimeout(window.tm);window.tm=setTimeout(()=>{S.q=e.target.value;render()},120)};$("refresh").onclick=()=>load(true);$("guide").onclick=guide;$("reminders").onclick=reminders;$("health").onclick=health;$("clean").onclick=cleaner;$("stats").onclick=stats;$("favOnly").onclick=()=>{S.fav=!S.fav;$("favOnly").classList.toggle("on",S.fav);render()};$("recentOnly").onclick=()=>{S.recent=!S.recent;$("recentOnly").classList.toggle("on",S.recent);render()};$("view").onclick=()=>{$("grid").classList.toggle("list");$("view").textContent=$("grid").classList.contains("list")?"▦":"☷"};
function theme(t){document.documentElement.dataset.theme=t;localStorage.setItem(KEY.theme,t);$("theme").textContent=t==="dark"?"☀️":"🌙"}theme(localStorage.getItem(KEY.theme)||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light"));$("theme").onclick=()=>theme(document.documentElement.dataset.theme==="dark"?"light":"dark");$("settings").onclick=settings;
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{let n=b.dataset.n;if(n==="settings")settings();else if(n==="guide")guide();else if(n==="fav")$("favOnly").click();else if(n==="live"){S.fav=S.recent=false;$("favOnly").classList.remove("on");$("recentOnly").classList.remove("on");render()}else scrollTo({top:0,behavior:"smooth"})});
let dp;addEventListener("beforeinstallprompt",e=>{e.preventDefault();dp=e;$("install").classList.remove("hide")});$("install").onclick=async()=>{await dp?.prompt();dp=null;$("install").classList.add("hide")};if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(console.warn));
sourceUI();load();setInterval(()=>load(true),Number(localStorage.getItem(KEY.refresh)||30)*60000);
